<?php
// AnimateCSS Control
return array(
      'type' => 'group',
      'heading' => __( 'FlatUX Animate' ),
      'options' => array(
		'animatecss'     => array(
			'type'    => 'select',
			'heading' => 'Animate',
			'default' => '',
			'options' => array(
				'' => 'None',
				'bounce' => 'Bounce',
				'flash' => 'Flash',
				'pulse' => 'Pulse',
				'rubberBand' => 'Rubber Band',
				'shakeX' => 'Shake X',
				'shakeY' => 'Shake Y',
				'headShake' => 'Head Shake',
				'swing' => 'Swing',
				'tada' => 'Tada',
				'wobble' => 'Wobble',
				'jello' => 'Jello',
				'heartBeat' => 'Heart Beat',
				'backInDown' => 'Back In Down',
				'backInLeft' => 'Back In Left',
				'backInRight' => 'Back In Right',
				'backInUp' => 'Back In Up',
				'Back exits' => 'Back Exits',
				'backOutDown' => 'Back Out Down',
				'backOutLeft' => 'Back Out Left',
				'backOutRight' => 'Back Out Right',
				'backOutUp' => 'Back Out Up',
				'bounceIn' => 'Bounce In',
				'bounceInDown' => 'Bounce In Down',
				'bounceInLeft' => 'Bounce In Left',
				'bounceInRight' => 'Bounce In Right',
				'bounceInUp' => 'Bounce In Up',
				'bounceOut' => 'Bounce Out',
				'bounceOutDown' => 'Bounce Out Down',
				'bounceOutLeft' => 'Bounce Out Left',
				'bounceOutRight' => 'Bounce Out Right',
				'bounceOutUp' => 'Bounce Out Up',
				'fadeIn' => 'Fade In',
				'fadeInDown' => 'Fade In Down',
				'fadeInDownBig' => 'Fade In Down Big',
				'fadeInLeft' => 'Fade In Left',
				'fadeInLeftBig' => 'Fade In Left Big',
				'fadeInRight' => 'Fade In Right',
				'fadeInRightBig' => 'Fade In Right Big',
				'fadeInUp' => 'Fade In Up',
				'fadeInUpBig' => 'Fade In Up Big',
				'fadeInTopLeft' => 'Fade In Top Left',
				'fadeInTopRight' => 'Fade In Top Right',
				'fadeInBottomLeft' => 'Fade In Bottom Left',
				'fadeInBottomRight' => 'Fade In Bottom Right',
				'fadeOut' => 'Fade Out',
				'fadeOutDown' => 'Fade Out Down',
				'fadeOutDownBig' => 'Fade Out Down Big',
				'fadeOutLeft' => 'Fade Out Left',
				'fadeOutLeftBig' => 'Fade Out Left Big',
				'fadeOutRight' => 'Fade Out Right',
				'fadeOutRightBig' => 'Fade Out Right Big',
				'fadeOutUp' => 'Fade Out Up',
				'fadeOutUpBig' => 'Fade Out Up Big',
				'fadeOutTopLeft' => 'Fade Out Top Left',
				'fadeOutTopRight' => 'Fade Out Top Right',
				'fadeOutBottomRight' => 'Fade Out Bottom Right',
				'fadeOutBottomLeft' => 'Fade Out Bottom Left',
				'flip' => 'Flip',
				'flipInX' => 'Flip In X',
				'flipInY' => 'Flip In Y',
				'flipOutX' => 'Flip Out X',
				'flipOutY' => 'Flip Out Y',
				'lightSpeedInRight' => 'Light Speed In Right',
				'lightSpeedInLeft' => 'Light Speed In Left',
				'lightSpeedOutRight' => 'Light Speed Out Right',
				'lightSpeedOutLeft' => 'Light Speed Out Left',
				'rotateIn' => 'Rotate In',
				'rotateInDownLeft' => 'Rotate In Down Left',
				'rotateInDownRight' => 'Rotate In Down Right',
				'rotateInUpLeft' => 'Rotate In Up Left',
				'rotateInUpRight' => 'Rotate In Up Right',
				'rotateOut' => 'Rotate Out',
				'rotateOutDownLeft' => 'Rotate Out Down Left',
				'rotateOutDownRight' => 'Rotate Out Down Right',
				'rotateOutUpLeft' => 'Rotate Out Up Left',
				'rotateOutUpRight' => 'Rotate Out Up Right',
				'hinge' => 'Hinge',
				'jackInTheBox' => 'Jack In TheBox',
				'rollIn' => 'Roll In',
				'rollOut' => 'Roll Out',
				'zoomIn' => 'Zoom In',
				'zoomInDown' => 'Zoom In Down',
				'zoomInLeft' => 'Zoom In Left',
				'zoomInRight' => 'Zoom In Right',
				'zoomInUp' => 'Zoom In Up',
				'zoomOut' => 'Zoom Out',
				'zoomOutDown' => 'Zoom Out Down',
				'zoomOutLeft' => 'Zoom Out Left',
				'zoomOutRight' => 'Zoom Out Right',
				'zoomOutUp' => 'Zoom Out Up',
				'slideInDown' => 'Slide In Down',
				'slideInLeft' => 'Slide In Left',
				'slideInRight' => 'Slide In Right',
				'slideInUp' => 'Slide In Up',
				'slideOutDown' => 'Slide Out Down',
				'slideOutLeft' => 'Slide Out Left',
				'slideOutRight' => 'Slide Out Right',
				'slideOutUp' => 'Slide Out Up',
			),
		),
		'animatecss_infinite'      => array(
			'conditions' => 'animatecss',
			'type'    => 'checkbox',
			'heading' => 'Infinite',
		),
		'animatecss_repeat'       => array(
			'conditions' => 'animatecss && animatecss_infinite == ""',
			'type'    => 'slider',
			'class'   => '',
			'heading' => 'Repeat',
			'default' => '0',
			'max'     => '60',
			'min'     => '0',
		),
		'animatecss_speed'       => array(
			'conditions' => 'animatecss',
			'type'    => 'select',
			'heading' => 'Speed',
			'default' => '',
			'options' => array(
				''          => 'Custom',
				'faster'   => 'Faster',
				'fast'      => 'Fast',
				'slow' => 'Slow',
				'slower'     => 'Slower',
			),
		),
		'animatecss_delay'       => array(
			'conditions' => 'animatecss && animatecss_speed == ""',
			'type'    => 'slider',
			'class'   => '',
			'heading' => 'Delay (s)',
			'default' => '0',
			'max'     => '60',
			'min'     => '0',
		),
		'animatecss_duration'       => array(
			'conditions' => 'animatecss && animatecss_speed == ""',
			'type'    => 'slider',
			'class'   => '',
			'heading' => 'Duration (s)',
			'default' => '0',
			'max'     => '60',
			'min'     => '0',
		),
),
);